<?php
/**
 * Created by PhpStorm.
 * User: sikwansing
 * Date: 2021/1/14
 * Time: 22:56
 */

namespace app\admin\controller;

use app\BaseController;
use think\exception\HttpResponseException;

class AdminBase extends  BaseController
{
    public $adminUser = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 判断是否登录
        /*if($this->isLogin() == false){ // 放到中间件auth中
            return redirect(url("login/index"), 302);
        }*/
    }

    /**
     * 判断是否登录
     * @return bool
     */
    public function isLogin(){
        $this->adminUser = session(config('admin.session_admin'));
        if(empty($this->adminUser)){
            return false;
        }
        else{
            return true;
        }
    }
    public function redirect(...$args){
        throw new HttpResponseException(redirect(...$args));
    }
}