<?php
/**
 * 无需登录的场景继承此控制器
 * 要登录的场景继承AuthBase控制器
 */

namespace app\api\controller;


use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends BaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function show(...$args){
        throw new HttpResponseException(show(...$args));
    }
}