<?php


namespace app\api\controller;


class AuthBase extends ApiBase
{
    public $accessToken = null;
    public $userId = null;
    public $userName = null;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessToken = $this->request->header('access-token');
        if(!$this->accessToken || !$this->isLogin()){
            return $this->show(config('status.not_login'), 'not login');
        }
    }
    public function isLogin(){
        $userInfo = cache(config('redis.token_pre').$this->accessToken);
        if(!$userInfo){
            return false;
        }
        if(!empty($userInfo['id']) && !empty($userInfo['username'])){
            $this->userName = $userInfo['username'];
            $this->userId = $userInfo['id'];
            return true;
        }
        return false;
    }
}